name: Cloud Function Deployment

on:
  push:
    branches:
      - main
jobs:
  dev_deployment:
    name: Development Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: api-ingest
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: us-central1
          entry_point: HelloWorld
          runtime: java17
          env_vars: "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
